const std = @import("std");
const zt = @import("zt");

pub fn main(init: std.process.Init) !void {
    var arguments = try std.process.Args.Iterator.initAllocator(
        init.minimal.args,
        init.gpa,
    );
    defer arguments.deinit();
    _ = arguments.skip();

    const input_path = arguments.next() orelse return error.MissingInputPath;
    const output_path = arguments.next() orelse return error.MissingOutputPath;
    if (arguments.next() != null) return error.UnexpectedArgument;

    try compileTemplate(
        init.io,
        init.gpa,
        input_path,
        output_path,
    );
}

fn compileTemplate(
    io: std.Io,
    allocator: std.mem.Allocator,
    input_path: []const u8,
    output_path: []const u8,
) !void {
    var arena = std.heap.ArenaAllocator.init(allocator);
    defer arena.deinit();
    const temporary_allocator = arena.allocator();
    const source = try std.Io.Dir.cwd().readFileAlloc(
        io,
        input_path,
        temporary_allocator,
        .limited(10 * 1024 * 1024),
    );

    var parser = zt.Parser.init(temporary_allocator, source);
    const template_file = parser.parseFile() catch |err| {
        if (parser.err) |parse_error| {
            std.debug.print(
                "{s}:{d}:{d}: {s}\n",
                .{ input_path, parse_error.line, parse_error.col, parse_error.msg },
            );
        }
        return err;
    };

    var output: std.Io.Writer.Allocating = .init(temporary_allocator);
    try output.writer.writeAll("// Auto-generated by zt; do not edit.\n");
    try output.writer.writeAll("const std = @import(\"std\");\n");
    try output.writer.writeAll("const zt = @import(\"zt\");\n\n");
    var generator = zt.Generator.init(&output.writer);
    generator.source_file = std.fs.path.basename(input_path);
    try generator.generateFile(template_file);

    try std.Io.Dir.cwd().writeFile(io, .{
        .sub_path = output_path,
        .data = output.written(),
    });
}
